name: Claude Assistant
permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write
  actions: read
  metadata: read

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned, labeled]
  workflow_dispatch:

jobs:
  claude-response:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Claude Code Action Official
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
