name: Claude Code Workflow
on: [push, pull_request]

jobs:
  claude-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Claude Code Action Official
        uses: anthropics/claude-code-action@v1
